#!/usr/bin/env zsh

set -uo pipefail
# -u prevent using undefined variables
# -o pipefail force pipelines to fail on first non-zero status code

IFS=$'\n\t'
# Set Internal Field Separator to newlines and tabs
# This makes bash consider newlines and tabs as separating words
# See: http://redsymbol.net/articles/unofficial-bash-strict-mode/


# declare -a SEARCH_TERMS

# while IFS= read -r SEARCH_TERM; do
#   SEARCH_TERMS+=("${SEARCH_TERM}")
# done < "../Code/search/search_terms"

declare -r SEARCH_TERM="${1}"

if [[ $# -eq 0 ]] ; then
    echo "No arguemnts given"
    exit 1
fi

# for SEARCH_TERM in "${SEARCH_TERMS[@]}"; do

  echo "0" >  ../Code/search/counter
  echo "[${SEARCH_TERM}]"
  for DIR in *; do
    (
      cd "${DIR}" || exit 1
      
      for PDF in *; do
          if pdfgrep --max-count 1 --files-with-matches --ignore-case "${SEARCH_TERM}" "${PDF}" >/dev/null; then
          # if pdfgrep --after-context=6 --before-context=6 --ignore-case "${SEARCH_TERM}" "${PDF}"; then
            COUNTER=$[$(cat ../../Code/search/counter) + 1]
            echo "${COUNTER}" > ../../Code/search/counter
            break
          fi
      done
    )
  done

echo "${SEARCH_TERM} = $(cat ../Code/search/counter)"

# done

